### ISSUE TITLE
SymbiFlow Installation for OSS Synthesis

### ISSUE THREAD

**Issue by cjearls** [carlosedp/chisel-playground#11]
How did you setup the SymbiFlow tools to run the "arty7-35t-oss" target? I tried setting them up with the example in the symbiflow-examples repo, but when I run conda, I get an error when trying to import fusesoc. If I can get the tools working, I can add support for a "nexys4ddr-oss" target.

**Comment by carlosedp** [comment]
I use it on a Docker container I built locally and this Edalize launcher: https://gist.github.com/carlosedp/c0e29d55e48309a48961f2e3939acfe9
Here is the Dockefile and script used in it: https://gist.github.com/carlosedp/1f9119e0645e842e474ec1a67b5aed7e

**Comment by carlosedp** [comment]
I wrote a post about this: https://carlosedp.medium.com/xilinx-open-source-fpga-toolchain-on-docker-containers-93202650a615
Hope it helps!
