### ISSUE TITLE
help me check the dev board

### ISSUE THREAD

**Issue by fatalfeel** [carlosedp/chisel-playground#13]
If I want to try your example. 
Is the dev board same as yours?
https://www.mouser.tw/ProductDetail/Digilent/410-319?qs=%2Fha2pyFadujnBm65lk7kC3Nxr5Hc60cmLOa3GzRyYN3Km3DyZEW2uQ%3D%3D

**Comment by carlosedp** [comment]
Yes, it's the same. In the chiselblink project it's the `artya7-35t` using Vivado or `artya7-35t-oss` using Symbiflow targets.

**Comment by fatalfeel** [comment]
Thank u sir
