### ISSUE TITLE
feature request run example on IntelliJ IDEA

### ISSUE THREAD

**Issue by fatalfeel** [carlosedp/chisel-playground#14]
apt install sbt
IntelliJ IDEA Community Edition

debug scala and generate .v in  IntelliJ IDEA

**Comment by carlosedp** [comment]
Sorry but I don't use IntelliJ as a dev environment. I develop on VSCode but the tools here doesn't depend on the IDE as it's all command line.

**Comment by fatalfeel** [comment]
Chisel design Risc-V cpu
https://fatalfeel.blogspot.com/2013/12/chisel-design-ic-for-risc-v.html
or
https://github.com/ekiwi/icesugar-chisel

how about those? maybe yours can do that well
